###
# create a user 
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "email": "reyes.marq@gmail.com",
  "password": "reyes859"
}

###
# Login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "reyes.marq@gmail.coms",
  "password": "reyes859"
}

###
# get Users with auth
GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1Zjk3MWRhYWM3OTI0ZjU5MjBiYWJmZjQiLCJpYXQiOjE2MDM4NDUwMTksImV4cCI6MTYwMzg0NTkxOX0.oODM3mkS6YQydtPrFBoKhF3Q43CuNAcZo_JBKWfzLKw

###
# get Users with no auth
GET http://localhost:3000/api/users/usersNoAuth
Content-Type: application/json

###
# refresh token
POST http://localhost:3000/api/users/refreshToken
Content-Type: application/json
Cookie: jid=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1Zjk3MWRhYWM3OTI0ZjU5MjBiYWJmZjQiLCJ0b2tlblZlcnNpb24iOjAsImlhdCI6MTYwMzgzOTYxNSwiZXhwIjoxNjA0NDQ0NDE1fQ.MKh2G91F5X9M0Wp0hOmBoLUE-RbcNyiY-iFczhlRTuI;

###
# revoke refresh token
POST http://localhost:3000/api/users/revokeRefreshTokenForUser
Content-Type: application/json

{
  "userId": "5f9372cc742ce5a33ceeb4e4"
}